
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./backend:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - "8088:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./.docker/php
    volumes:
      - ./backend:/var/www/html
    # environment:
    #   PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 200M
    volumes:
      - ./phpmyadmin/phpmyadmin.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  mysql-data: