version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./backend:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./.docker/php
    volumes:
      - ./backend:/var/www/html
    # environment:
    #   PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stick_shop
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: